apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mrs8cj3tv-nodejs 
  janus-idp.io/tekton: mrs8cj3tv-nodejs
  backstage.io/kubernetes-id: mrs8cj3tv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mrs8cj3tv-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  