apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mrs8cj3tv-nodejs
  janus-idp.io/tekton: mrs8cj3tv-nodejs
  backstage.io/kubernetes-id: mrs8cj3tv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mrs8cj3tv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
