apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mrs8cj3tv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mrs8cj3tv-nodejs 
  name: mrs8cj3tv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mrs8cj3tv-nodejs 
